---
- name: firewalld
  hosts: localhost
  gather_facts: no

  tasks:
    - name: port allow
      shell: |
        sudo firewall-cmd --zone=public --permanent --add-port={{ port }}/tcp
        sudo firewall-cmd --reload
      delegate_to: "{{ server }}"
      ignore_errors: yes

    - name: port listen
      shell:
        cmd: iptables -S | grep {{ port }}
      delegate_to: "{{ server }}"
      ignore_errors: yes
